using Pkg
Pkg.generate("Replication")
Pkg.activate("Replication")
Pkg.add("MAT")
Pkg.add("Statistics")
Pkg.add("DelimitedFiles")
Pkg.add("Random")
Pkg.add("LinearAlgebra")
Pkg.add(PackageSpec(name = "MAT", version ="0.10.5")) 
Pkg.add(PackageSpec(name = "CSV", version ="0.10.7"))
Pkg.add(PackageSpec(name = "JuMP", version ="1.4.0"))
Pkg.add(PackageSpec(name = "DataFrames", version ="1.3.6"))
Pkg.add(PackageSpec(name = "StatsBase", version = "0.33.21"))
Pkg.add(PackageSpec(name = "Plots", version = "1.37.0"))
Pkg.add(PackageSpec(name = "XLSX", version = "0.9.0 "))
Pkg.add(PackageSpec(name = "HypothesisTests", version = "0.10.11"))
Pkg.add(PackageSpec(name = "LaTeXStrings",  version = "1.3.0"))
Pkg.add(PackageSpec(name = "Gurobi", version ="0.11.4"))
using CSV, DelimitedFiles,JuMP, Gurobi, DataFrames, Random, DataFrames, LinearAlgebra, StatsBase,Statistics, Plots, XLSX, HypothesisTests,LaTeXStrings,MAT
